services:


  python:
    image: python:latest
    container_name: python_container
    command: tail -f /dev/null
    volumes:
      - ./python-code:/app
    working_dir: /app
  c:
    image: gcc:latest
    container_name: c_container
    command: tail -f /dev/null
    volumes:
      - ./c-code:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "apt update && apt install -y gdb && tail -f /dev/null"]



  java:
    image: openjdk:latest
    container_name: java_container
    command: tail -f /dev/null
    volumes:
      - ./java-code:/app
    working_dir: /app
  postgresql:
      image: bitnami/postgresql
      restart: always
      ports:
        - '5432:5432'
      volumes:
        - postgresql_data:/bitnami/postgresql
      environment:
        - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
        - POSTGRESQL_LOG_HOSTNAME=true
        - POSTGRESQL_REPLICATION_MODE=master
        - POSTGRESQL_REPLICATION_USER=repl_user
        - POSTGRESQL_REPLICATION_PASSWORD=repl_user
        - POSTGRESQL_USERNAME=postgres
        - POSTGRESQL_PASSWORD=postgres
        - POSTGRESQL_DATABASE=development_database
        - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgresql_data:
    driver: local